# Generated by Django 5.0.1 on 2025-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='publish_date',
            field=models.SmallIntegerField(blank=True, help_text='Year of publication', null=True),
        ),
    ]
