# Generated by Django 5.0.1 on 2025-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookitem_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='publish_date',
            field=models.DateField(blank=True, help_text='Year of publication', null=True),
        ),
    ]
