# Generated by Django 5.0.1 on 2025-02-25 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmeteo', '0004_alter_htheitem_lat_alter_htheitem_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HTheItem',
            new_name='MeteoItem',
        ),
    ]
