# Generated by Django 5.0.1 on 2024-01-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='before'),
            preserve_default=False,
        ),
    ]
