# Generated by Django 5.0.1 on 2024-01-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=144),
        ),
    ]
