# Generated by Django 5.0.1 on 2024-01-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_blogpost_publish_date_blogpost_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
