# Generated by Django 5.0.1 on 2025-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='category',
            field=models.CharField(choices=[('courses', 'Courses'), ('livraison', 'Livraison'), ('transport', 'Transport')], default='courses', max_length=20),
        ),
        migrations.AddField(
            model_name='demandes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandes',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
